version: "3.9"
services:
  service:
    image: demo/betting-service
    container_name: betting-service
    ports:
      - 8080:8080
    environment:
      spring.datasource.url: jdbc:postgresql://database:5432/betting
      awesome.wallet.url: http://wallet:8080
    links:
      - database
      - wallet
    depends_on:
      - database
  database:
    image: demo/betting-db
    container_name: betting-db
    ports:
      - 5433:5432
  wallet:
    image: rodolpheche/wiremock
    container_name: betting-wallet-stub
    volumes:
      - ./src/test/resources/stubs/:/home/wiremock
    ports:
      - 8082:8080